name:                db-monitor
version:             0.1.0
github:              "viviag/dbmonitor"
license:             BSD3
author:              "Vitalii Guzeev"
maintainer:          "viviag@yandex.ru"
copyright:           "2021 Vitalii Guzeev"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis: Tool performing periodic checks of data invariants which are hard or impossible to be imposed by constraints. For Postgres only.
category: Monitoring, Database

description: Please see the README on GitHub at <https://github.com/viviag/dbmonitor#readme>

dependencies:
- ansi-terminal        >= 0.11.3 && < 0.12
- base                 >= 4.12.0 && <= 4.15.1.0
- async                >= 2.2.2 && < 2.3
- bytestring           >= 0.10.8 && < 0.11
- text                 >= 1.2.3 && < 1.3
- stm                  >= 2.5.0 && < 2.6
- dhall                >= 1.40.2 && < 1.42
- time                 >= 1.8.0 && <= 1.9.3
- unordered-containers >= 0.2.10 && < 0.3
- vector               >= 0.12.0 && < 0.13
- filepath             >= 1.4.2 && < 1.5
- directory            >= 1.3.3 && < 1.4
- mtl                  >= 2.2.2 && < 2.3
- optparse-applicative >= 0.16.1.0 && < 0.18
- hasql                >= 1.4.4 && <= 1.5.0.5
- fsnotify             >= 0.3.0 && < 0.4
- lifted-base          >= 0.2.3 && < 0.3
- monad-control        >= 1.0.3 && < 1.1
- transformers-base    >= 0.4.6 && < 0.5
- telegram-bot-simple  >= 0.4.5 && < 0.6
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

executables:
  dbmonitor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -eventlog
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - db-monitor
