name:                db-monitor
version:             0.1.0
github:              "viviag/dbmonitor"
license:             BSD3
author:              "Vitalii Guzeev"
maintainer:          "viviag@yandex.ru"
copyright:           "2021 Vitalii Guzeev"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis: Tool performing periodic checks of data invariants which are hard or impossible to be imposed by constraints. For Postgres only.
category: Monitoring

description: Please see the README on GitHub at <https://github.com/viviag/dbmonitor#readme>

dependencies:
- base >= 4.7
- lifted-base
- transformers-base
- monad-control
- mtl
- stm
- async
- bytestring
- text
- vector
- time
- unordered-containers
- dhall
- telegram-bot-simple
- hasql
- optparse-applicative
- hinotify
- directory
- filepath
- ansi-terminal

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

executables:
  dbmonitor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -eventlog
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - db-monitor
